### ISSUE TITLE
add thread/cpu as arg in ds-cgpwgs.pl (ds-wrapper.pl)

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/dockstore-cgpwgs#18]
Make more obvious how to use rather than just the CPU env variable.

**Comment by jsmedmar** [comment]
Wondering if `OUTPUT_DIR` should also be an option?

**Comment by jsmedmar** [comment]
Nevermind, using `HOME` should be enough

**Comment by keiranmraine** [comment]
Both are already added to the in development branch: https://github.com/cancerit/dockstore-cgpwgs/blob/feature/fragmentReadQc/scripts/ds-cgpwgs.pl#L37-L38

**Comment by leiendeckerlu** [comment]
Hi there,

I think it is the best to reopen this issue here for my question:

I was wondering how to tell ds-wrapper.pl the number of available cores in our system?

I'm using cgpwgs with singularity on our HPC system. In the cwl config file I found this part and I'm now wondering how I can directly tell the wrapper script to use those settings?

> hints:
>   - class: ResourceRequirement
>     coresMin: 1 # works but long, 24 recommended
>     ramMin: 32000
>     outdirMin: 20000

Many thanks!
Lukas

**Comment by keiranmraine** [comment]
The release has been delayed slightly due to some upstream issues, the option will be released very soon and you can see it here:

https://github.com/cancerit/dockstore-cgpwgs/blob/feature/fragmentReadQc/scripts/ds-cgpwgs.pl#L289

**Comment by keiranmraine** [comment]
Done
