### ISSUE TITLE
Can't use container to complete Battenberg analysis

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/dockstore-cgpwgs#29]
It should be possible to use this container to process the partial run of battenberg (just alleleCounts) through to completion.

https://github.com/cancerit/cgpBattenberg/issues/82 indicates that this is not possible.

Diagnose and fix.

@leiendeckerlu

**Comment by dk-crazydiv** [comment]
I am facing the same issue. Since I'm new to battenberg repo & cgpBattenberg repo I am unable to figure out how to fix the error, can someone please help? 
The error actually comes when executing _Sanger_CGP_Battenberg_Implement_battenberg_runbaflog.0.sh_ 

Here's the error from file Sanger_CGP_Battenberg_Implement_battenberg_runbaflog.0.err
`Error in library(Battenberg) : there is no package called 'Battenberg'
`
I'm facing the same error on **1.1.0**, **1.1.3** and **release_2.1.0** tags on quay.io

Inside docker container, I cloned cgpBattenberg with git head on realease matching the docker's battenberg version and tried installing Rsupport/setup.sh but that also doesn't seem to install Battenberg package. Any ideas on how to resolve the issue? 

Current hack I am using invovles using release 0.1.0 to perform the first 3 steps in the pipeline and then use 1.1.0 (manually installing some missing softwares like impute2) to continue and complete the analysis to 'finalise' step. It would really be helpful if someone can point me on how to fix "No package called Battenberg" error in latest releases.
